// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *home → s1 images*
 */
export interface HomeDocumentDataS1SliderItem {
  /**
   * label field in *home → s1 images*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s1_slider[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * image field in *home → s1 images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s1_slider[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *home → s2 icons*
 */
export interface HomeDocumentDataS2IconsItem {
  /**
   * label field in *home → s2 icons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s2_icons[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * icon field in *home → s2 icons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s2_icons[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Item in *home → s5 slider*
 */
export interface HomeDocumentDataS5SliderItem {
  /**
   * icon field in *home → s5 slider*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s5_slider[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * testimonial field in *home → s5 slider*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s5_slider[].testimonial
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testimonial: prismic.KeyTextField;

  /**
   * attribution field in *home → s5 slider*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s5_slider[].attribution
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  attribution: prismic.KeyTextField;
}

/**
 * Item in *home → partners*
 */
export interface HomeDocumentDataPartnersItem {
  /**
   * logo field in *home → partners*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.partners[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Item in *home → s7 cities*
 */
export interface HomeDocumentDataS7CitiesItem {
  /**
   * image field in *home → s7 cities*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s7_cities[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * label field in *home → s7 cities*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s7_cities[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

type HomeDocumentDataSlicesSlice = never;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * hero_image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * title line one field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.title_line_one
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_line_one: prismic.KeyTextField;

  /**
   * title line two field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.title_line_two
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_line_two: prismic.KeyTextField;

  /**
   * hero subtitle field in *home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.hero_subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  hero_subtitle: prismic.RichTextField;

  /**
   * hero button field in *home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.hero_button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  hero_button: prismic.LinkField;

  /**
   * s1 eyebrow field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s1_eyebrow
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s1_eyebrow: prismic.KeyTextField;

  /**
   * s1_body field in *home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s1_body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  s1_body: prismic.RichTextField;

  /**
   * s1 images field in *home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s1_slider[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  s1_slider: prismic.GroupField<Simplify<HomeDocumentDataS1SliderItem>>;

  /**
   * s1 static image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s1_static_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s1_static_image: prismic.ImageField<never>;

  /**
   * s2 eyebrow field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s2_eyebrow
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s2_eyebrow: prismic.KeyTextField;

  /**
   * s2 icons field in *home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s2_icons[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  s2_icons: prismic.GroupField<Simplify<HomeDocumentDataS2IconsItem>>;

  /**
   * s3 icon field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s3_icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s3_icon: prismic.ImageField<never>;

  /**
   * s3 title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s3_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s3_title: prismic.KeyTextField;

  /**
   * s3 body field in *home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s3_body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  s3_body: prismic.RichTextField;

  /**
   * s3 button field in *home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s3_button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  s3_button: prismic.LinkField;

  /**
   * s3 image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s3_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s3_image: prismic.ImageField<never>;

  /**
   * s4 icon field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s4_icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s4_icon: prismic.ImageField<never>;

  /**
   * s4 title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s4_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s4_title: prismic.KeyTextField;

  /**
   * s4 body field in *home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s4_body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  s4_body: prismic.RichTextField;

  /**
   * s4 button field in *home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s4_button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  s4_button: prismic.LinkField;

  /**
   * s4 image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s4_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s4_image: prismic.ImageField<never>;

  /**
   * s5 background image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s5_background_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s5_background_image: prismic.ImageField<never>;

  /**
   * s5 eyebrow field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s5_eyebrow
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s5_eyebrow: prismic.KeyTextField;

  /**
   * s5 slider field in *home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s5_slider[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  s5_slider: prismic.GroupField<Simplify<HomeDocumentDataS5SliderItem>>;

  /**
   * s6 eyebrow field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s6_eyebrow
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s6_eyebrow: prismic.KeyTextField;

  /**
   * s6 body field in *home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s6_body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  s6_body: prismic.RichTextField;

  /**
   * s6 button field in *home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s6_button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  s6_button: prismic.LinkField;

  /**
   * partners field in *home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.partners[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  partners: prismic.GroupField<Simplify<HomeDocumentDataPartnersItem>>;

  /**
   * s7 eyebrow field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s7_eyebrow
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s7_eyebrow: prismic.KeyTextField;

  /**
   * s7 body field in *home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s7_body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  s7_body: prismic.RichTextField;

  /**
   * s7 button field in *home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s7_button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  s7_button: prismic.LinkField;

  /**
   * s7 cities field in *home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s7_cities[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  s7_cities: prismic.GroupField<Simplify<HomeDocumentDataS7CitiesItem>>;

  /**
   * s8 background field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s8_background
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s8_background: prismic.ImageField<never>;

  /**
   * s8 title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s8_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s8_title: prismic.KeyTextField;

  /**
   * s8 button field in *home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.s8_button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  s8_button: prismic.LinkField;

  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *nav → partners*
 */
export interface NavDocumentDataPartnersItem {
  /**
   * logo field in *nav → partners*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.partners[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Item in *nav → visit_addresses*
 */
export interface NavDocumentDataVisitAddressesItem {
  /**
   * address field in *nav → visit_addresses*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.visit_addresses[].address
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  address: prismic.RichTextField;
}

/**
 * Content for nav documents
 */
interface NavDocumentData {
  /**
   * logo full field in *nav*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.logo_full
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_full: prismic.ImageField<never>;

  /**
   * logo small field in *nav*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.logo_small
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_small: prismic.ImageField<never>;

  /**
   * left link field in *nav*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.left_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  left_link: prismic.LinkField;

  /**
   * nav links field in *nav*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.nav_links
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  nav_links: prismic.Repeatable<prismic.LinkField>;

  /**
   * partners field in *nav*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.partners[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  partners: prismic.GroupField<Simplify<NavDocumentDataPartnersItem>>;

  /**
   * visit_addresses field in *nav*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.visit_addresses[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  visit_addresses: prismic.GroupField<
    Simplify<NavDocumentDataVisitAddressesItem>
  >;

  /**
   * telephone field in *nav*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.telephone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  telephone: prismic.KeyTextField;

  /**
   * mailingAddress field in *nav*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.mailingaddress
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  mailingaddress: prismic.RichTextField;
}

/**
 * nav document from Prismic
 *
 * - **API ID**: `nav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<NavDocumentData>, "nav", Lang>;

type PageDocumentDataSlicesSlice = RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = HomeDocument | NavDocument | PageDocument;

/**
 * Primary content in *ContentWidth → Single Col Text → Primary*
 */
export interface ContentWidthMediaSliceDefaultPrimary {
  /**
   * title field in *ContentWidth → Single Col Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * icon field in *ContentWidth → Single Col Text → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.default.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * top text field in *ContentWidth → Single Col Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.default.primary.top_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  top_text: prismic.RichTextField;

  /**
   * middle text field in *ContentWidth → Single Col Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.default.primary.middle_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  middle_text: prismic.RichTextField;

  /**
   * bottom text field in *ContentWidth → Single Col Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.default.primary.bottom_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bottom_text: prismic.RichTextField;

  /**
   * button one text field in *ContentWidth → Single Col Text → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.default.primary.button_one_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_one_text: prismic.KeyTextField;

  /**
   * button one link field in *ContentWidth → Single Col Text → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.default.primary.button_one_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_one_link: prismic.LinkField;

  /**
   * button two text field in *ContentWidth → Single Col Text → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.default.primary.button_two_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_two_text: prismic.KeyTextField;

  /**
   * button two link field in *ContentWidth → Single Col Text → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.default.primary.button_two_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_two_link: prismic.LinkField;

  /**
   * background color field in *ContentWidth → Single Col Text → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;

  /**
   * background_image field in *ContentWidth → Single Col Text → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * text float field in *ContentWidth → Single Col Text → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: left
   * - **API ID Path**: content_width_media.default.primary.text_float
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_float: prismic.SelectField<"left" | "right" | "center", "filled">;

  /**
   * text box position vertical field in *ContentWidth → Single Col Text → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: top
   * - **API ID Path**: content_width_media.default.primary.text_box_position_vertical
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_box_position_vertical: prismic.SelectField<
    "top" | "bottom" | "center",
    "filled"
  >;

  /**
   * text box position horizontal field in *ContentWidth → Single Col Text → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: left
   * - **API ID Path**: content_width_media.default.primary.text_box_position_horizontal
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_box_position_horizontal: prismic.SelectField<
    "left" | "right" | "center",
    "filled"
  >;

  /**
   * vimeo_id field in *ContentWidth → Single Col Text → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.default.primary.vimeo_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  vimeo_id: prismic.KeyTextField;

  /**
   * loopVideo field in *ContentWidth → Single Col Text → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: content_width_media.default.primary.loopvideo
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  loopvideo: prismic.BooleanField;
}

/**
 * Single Col Text variation for ContentWidth Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentWidthMediaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentWidthMediaSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ContentWidth → Text Slider Left - Image Right → Primary*
 */
export interface ContentWidthMediaSliceSliderLeftImageRightPrimary {
  /**
   * background color field in *ContentWidth → Text Slider Left - Image Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.sliderLeftImageRight.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  background_color: prismic.KeyTextField;

  /**
   * image right field in *ContentWidth → Text Slider Left - Image Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.sliderLeftImageRight.primary.image_right
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_right: prismic.ImageField<never>;

  /**
   * vimeo_id field in *ContentWidth → Text Slider Left - Image Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.sliderLeftImageRight.primary.vimeo_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  vimeo_id: prismic.KeyTextField;

  /**
   * loopVideo field in *ContentWidth → Text Slider Left - Image Right → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: content_width_media.sliderLeftImageRight.primary.loopvideo
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  loopvideo: prismic.BooleanField;
}

/**
 * Primary content in *ContentWidth → Items*
 */
export interface ContentWidthMediaSliceSliderLeftImageRightItem {
  /**
   * icon field in *ContentWidth → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * top text field in *ContentWidth → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.items[].top_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  top_text: prismic.RichTextField;

  /**
   * middle text field in *ContentWidth → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.items[].middle_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  middle_text: prismic.RichTextField;

  /**
   * bottom text field in *ContentWidth → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.items[].bottom_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bottom_text: prismic.RichTextField;

  /**
   * button one text field in *ContentWidth → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.items[].button_one_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_one_text: prismic.KeyTextField;

  /**
   * button one link field in *ContentWidth → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.items[].button_one_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_one_link: prismic.LinkField;

  /**
   * button two text field in *ContentWidth → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.items[].button_two_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_two_text: prismic.KeyTextField;

  /**
   * button two link field in *ContentWidth → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.items[].button_two_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_two_link: prismic.LinkField;
}

/**
 * Text Slider Left - Image Right variation for ContentWidth Slice
 *
 * - **API ID**: `sliderLeftImageRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentWidthMediaSliceSliderLeftImageRight =
  prismic.SharedSliceVariation<
    "sliderLeftImageRight",
    Simplify<ContentWidthMediaSliceSliderLeftImageRightPrimary>,
    Simplify<ContentWidthMediaSliceSliderLeftImageRightItem>
  >;

/**
 * Primary content in *ContentWidth → Two Col Image and Text → Primary*
 */
export interface ContentWidthMediaSliceTwoColImageAndTextPrimary {
  /**
   * icon field in *ContentWidth → Two Col Image and Text → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.twoColImageAndText.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * top text field in *ContentWidth → Two Col Image and Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.twoColImageAndText.primary.top_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  top_text: prismic.RichTextField;

  /**
   * middle text field in *ContentWidth → Two Col Image and Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.twoColImageAndText.primary.middle_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  middle_text: prismic.RichTextField;

  /**
   * bottom text field in *ContentWidth → Two Col Image and Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.twoColImageAndText.primary.bottom_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bottom_text: prismic.RichTextField;

  /**
   * button one text field in *ContentWidth → Two Col Image and Text → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.twoColImageAndText.primary.button_one_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_one_text: prismic.KeyTextField;

  /**
   * button one link field in *ContentWidth → Two Col Image and Text → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.twoColImageAndText.primary.button_one_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_one_link: prismic.LinkField;

  /**
   * button two text field in *ContentWidth → Two Col Image and Text → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.twoColImageAndText.primary.button_two_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_two_text: prismic.KeyTextField;

  /**
   * button two link field in *ContentWidth → Two Col Image and Text → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.twoColImageAndText.primary.button_two_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_two_link: prismic.LinkField;

  /**
   * background color field in *ContentWidth → Two Col Image and Text → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.twoColImageAndText.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;

  /**
   * background_image field in *ContentWidth → Two Col Image and Text → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.twoColImageAndText.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * text float field in *ContentWidth → Two Col Image and Text → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: left
   * - **API ID Path**: content_width_media.twoColImageAndText.primary.text_float
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_float: prismic.SelectField<"left" | "right" | "center", "filled">;

  /**
   * text box position vertical field in *ContentWidth → Two Col Image and Text → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: top
   * - **API ID Path**: content_width_media.twoColImageAndText.primary.text_box_position_vertical
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_box_position_vertical: prismic.SelectField<
    "top" | "bottom" | "center",
    "filled"
  >;

  /**
   * text box position horizontal field in *ContentWidth → Two Col Image and Text → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: left
   * - **API ID Path**: content_width_media.twoColImageAndText.primary.text_box_position_horizontal
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_box_position_horizontal: prismic.SelectField<
    "left" | "right" | "center",
    "filled"
  >;

  /**
   * vimeo_id field in *ContentWidth → Two Col Image and Text → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_media.twoColImageAndText.primary.vimeo_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  vimeo_id: prismic.KeyTextField;

  /**
   * loopVideo field in *ContentWidth → Two Col Image and Text → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: content_width_media.twoColImageAndText.primary.loopvideo
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  loopvideo: prismic.BooleanField;

  /**
   * image sides field in *ContentWidth → Two Col Image and Text → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: content_width_media.twoColImageAndText.primary.image_sides
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  image_sides: prismic.BooleanField;
}

/**
 * Two Col Image and Text variation for ContentWidth Slice
 *
 * - **API ID**: `twoColImageAndText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentWidthMediaSliceTwoColImageAndText =
  prismic.SharedSliceVariation<
    "twoColImageAndText",
    Simplify<ContentWidthMediaSliceTwoColImageAndTextPrimary>,
    never
  >;

/**
 * Slice variation for *ContentWidth*
 */
type ContentWidthMediaSliceVariation =
  | ContentWidthMediaSliceDefault
  | ContentWidthMediaSliceSliderLeftImageRight
  | ContentWidthMediaSliceTwoColImageAndText;

/**
 * ContentWidth Shared Slice
 *
 * - **API ID**: `content_width_media`
 * - **Description**: ContentWidthMedia
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentWidthMediaSlice = prismic.SharedSlice<
  "content_width_media",
  ContentWidthMediaSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * logo field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * background image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<"desktop">;

  /**
   * vimeo id field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.vimeo_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  vimeo_id: prismic.KeyTextField;

  /**
   * top text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.top_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  top_text: prismic.RichTextField;

  /**
   * middle text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.middle_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  middle_text: prismic.RichTextField;

  /**
   * bottom text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.bottom_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bottom_text: prismic.RichTextField;

  /**
   * button one text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button_one_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_one_text: prismic.KeyTextField;

  /**
   * button one link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button_one_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_one_link: prismic.LinkField;

  /**
   * button two text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button_two_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_two_text: prismic.KeyTextField;

  /**
   * button two link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button_two_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_two_link: prismic.LinkField;

  /**
   * text box float field in *Hero → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: left
   * - **API ID Path**: hero.default.primary.text_box_float
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_box_float: prismic.SelectField<"left" | "right" | "center", "filled">;

  /**
   * text box vertical align field in *Hero → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: top
   * - **API ID Path**: hero.default.primary.text_box_vertical_align
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_box_vertical_align: prismic.SelectField<
    "top" | "bottom" | "center",
    "filled"
  >;

  /**
   * text justify field in *Hero → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: left
   * - **API ID Path**: hero.default.primary.text_align
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_align: prismic.SelectField<"left" | "right" | "center", "filled">;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → slider → Primary*
 */
export interface HeroSliceSliderPrimary {
  /**
   * logo field in *Hero → slider → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.slider.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * top text field in *Hero → slider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.slider.primary.top_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  top_text: prismic.RichTextField;

  /**
   * middle text field in *Hero → slider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.slider.primary.middle_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  middle_text: prismic.RichTextField;

  /**
   * bottom text field in *Hero → slider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.slider.primary.bottom_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bottom_text: prismic.RichTextField;

  /**
   * button one text field in *Hero → slider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.slider.primary.button_one_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_one_text: prismic.KeyTextField;

  /**
   * button one link field in *Hero → slider → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.slider.primary.button_one_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_one_link: prismic.LinkField;

  /**
   * button two text field in *Hero → slider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.slider.primary.button_two_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_two_text: prismic.KeyTextField;

  /**
   * button two link field in *Hero → slider → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.slider.primary.button_two_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_two_link: prismic.LinkField;

  /**
   * text box float field in *Hero → slider → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: left
   * - **API ID Path**: hero.slider.primary.text_box_float
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_box_float: prismic.SelectField<"left" | "right" | "center", "filled">;

  /**
   * text box vertical align field in *Hero → slider → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: top
   * - **API ID Path**: hero.slider.primary.text_box_vertical_align
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_box_vertical_align: prismic.SelectField<
    "top" | "bottom" | "center",
    "filled"
  >;

  /**
   * text justify field in *Hero → slider → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: left
   * - **API ID Path**: hero.slider.primary.text_align
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_align: prismic.SelectField<"left" | "right" | "center", "filled">;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceSliderItem {
  /**
   * background_image field in *Hero → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].backgorund_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  backgorund_image: prismic.ImageField<"desktop">;

  /**
   * vimeo_id field in *Hero → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].vimeo_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  vimeo_id: prismic.KeyTextField;
}

/**
 * slider variation for Hero Slice
 *
 * - **API ID**: `slider`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSlider = prismic.SharedSliceVariation<
  "slider",
  Simplify<HeroSliceSliderPrimary>,
  Simplify<HeroSliceSliderItem>
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceSlider;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *ThreeStepPlan → Default → Primary*
 */
export interface ThreeStepPlanSliceDefaultPrimary {
  /**
   * title field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * body field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * label step one field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.label_step_one
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label_step_one: prismic.RichTextField;

  /**
   * image step one field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.image_step_one
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_step_one: prismic.ImageField<never>;

  /**
   * top text step one field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.top_text_step_one
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  top_text_step_one: prismic.RichTextField;

  /**
   * bottom text step one field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.bottom_text_step_one
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bottom_text_step_one: prismic.RichTextField;

  /**
   * button one text step one field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.button_one_text_step_one
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_one_text_step_one: prismic.KeyTextField;

  /**
   * button one link step one field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.button_one_link_step_one
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_one_link_step_one: prismic.LinkField;

  /**
   * button two text step one field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.button_two_text_step_one
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_two_text_step_one: prismic.KeyTextField;

  /**
   * button two link step one field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.button_two_link_step_one
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_two_link_step_one: prismic.LinkField;

  /**
   * label step two field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.label_step_two
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label_step_two: prismic.RichTextField;

  /**
   * image step two field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.image_step_two
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_step_two: prismic.ImageField<never>;

  /**
   * top text step two field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.top_text_step_two
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  top_text_step_two: prismic.RichTextField;

  /**
   * bottom text step two field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.bottom_text_step_two
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bottom_text_step_two: prismic.RichTextField;

  /**
   * button one text step two field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.button_one_text_step_two
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_one_text_step_two: prismic.KeyTextField;

  /**
   * button one link step two field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.button_one_link_step_two
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_one_link_step_two: prismic.LinkField;

  /**
   * button two text step two field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.button_two_text_step_two
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_two_text_step_two: prismic.KeyTextField;

  /**
   * button two link step two field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.button_two_link_step_two
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_two_link_step_two: prismic.LinkField;

  /**
   * label step three field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.label_step_three
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label_step_three: prismic.RichTextField;

  /**
   * image step three field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.image_step_three
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_step_three: prismic.ImageField<never>;

  /**
   * top text step three field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.top_text_step_three
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  top_text_step_three: prismic.RichTextField;

  /**
   * bottom text step three field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.bottom_text_step_three
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bottom_text_step_three: prismic.RichTextField;

  /**
   * button one text step three field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.button_one_text_step_three
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_one_text_step_three: prismic.KeyTextField;

  /**
   * button one link step three field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.button_one_link_step_three
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_one_link_step_three: prismic.LinkField;

  /**
   * button two text step three field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.button_two_text_step_three
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_two_text_step_three: prismic.KeyTextField;

  /**
   * button two link step three field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.button_two_link_step_three
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_two_link_step_three: prismic.LinkField;

  /**
   * button one text field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.button_one_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_one_text: prismic.KeyTextField;

  /**
   * button one link field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.button_one_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_one_link: prismic.LinkField;

  /**
   * button two text field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.button_two_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_two_text: prismic.KeyTextField;

  /**
   * button two link field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.button_two_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_two_link: prismic.LinkField;

  /**
   * background color field in *ThreeStepPlan → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  background_color: prismic.KeyTextField;
}

/**
 * Default variation for ThreeStepPlan Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ThreeStepPlanSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ThreeStepPlanSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ThreeStepPlan → Clickthrough → Primary*
 */
export interface ThreeStepPlanSliceClickthroughPrimary {
  /**
   * title field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * body field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * label step one field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.label_step_one
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label_step_one: prismic.RichTextField;

  /**
   * image step one field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.image_step_one
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_step_one: prismic.ImageField<never>;

  /**
   * top text step one field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.top_text_step_one
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  top_text_step_one: prismic.RichTextField;

  /**
   * bottom text step one field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.bottom_text_step_one
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bottom_text_step_one: prismic.RichTextField;

  /**
   * button one text step one field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.button_one_text_step_one
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_one_text_step_one: prismic.KeyTextField;

  /**
   * button one link step one field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.button_one_link_step_one
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_one_link_step_one: prismic.LinkField;

  /**
   * button two text step one field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.button_two_text_step_one
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_two_text_step_one: prismic.KeyTextField;

  /**
   * button two link step one field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.button_two_link_step_one
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_two_link_step_one: prismic.LinkField;

  /**
   * label step two field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.label_step_two
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label_step_two: prismic.RichTextField;

  /**
   * image step two field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.image_step_two
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_step_two: prismic.ImageField<never>;

  /**
   * top text step two field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.top_text_step_two
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  top_text_step_two: prismic.RichTextField;

  /**
   * bottom text step two field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.bottom_text_step_two
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bottom_text_step_two: prismic.RichTextField;

  /**
   * button one text step two field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.button_one_text_step_two
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_one_text_step_two: prismic.KeyTextField;

  /**
   * button one link step two field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.button_one_link_step_two
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_one_link_step_two: prismic.LinkField;

  /**
   * button two text step two field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.button_two_text_step_two
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_two_text_step_two: prismic.KeyTextField;

  /**
   * button two link step two field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.button_two_link_step_two
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_two_link_step_two: prismic.LinkField;

  /**
   * label step three field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.label_step_three
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label_step_three: prismic.RichTextField;

  /**
   * image step three field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.image_step_three
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_step_three: prismic.ImageField<never>;

  /**
   * top text step three field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.top_text_step_three
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  top_text_step_three: prismic.RichTextField;

  /**
   * bottom text step three field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.bottom_text_step_three
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bottom_text_step_three: prismic.RichTextField;

  /**
   * button one text step three field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.button_one_text_step_three
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_one_text_step_three: prismic.KeyTextField;

  /**
   * button one link step three field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.button_one_link_step_three
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_one_link_step_three: prismic.LinkField;

  /**
   * button two text step three field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.button_two_text_step_three
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_two_text_step_three: prismic.KeyTextField;

  /**
   * button two link step three field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.button_two_link_step_three
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_two_link_step_three: prismic.LinkField;

  /**
   * button one text field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.button_one_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_one_text: prismic.KeyTextField;

  /**
   * button one link field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.button_one_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_one_link: prismic.LinkField;

  /**
   * button two text field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.button_two_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_two_text: prismic.KeyTextField;

  /**
   * button two link field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.button_two_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_two_link: prismic.LinkField;

  /**
   * background color field in *ThreeStepPlan → Clickthrough → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.clickthrough.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  background_color: prismic.KeyTextField;
}

/**
 * Clickthrough variation for ThreeStepPlan Slice
 *
 * - **API ID**: `clickthrough`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ThreeStepPlanSliceClickthrough = prismic.SharedSliceVariation<
  "clickthrough",
  Simplify<ThreeStepPlanSliceClickthroughPrimary>,
  never
>;

/**
 * Primary content in *ThreeStepPlan → Slider → Primary*
 */
export interface ThreeStepPlanSliceSliderPrimary {
  /**
   * title field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * body field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * label step one field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.label_step_one
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label_step_one: prismic.RichTextField;

  /**
   * image step one field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.image_step_one
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_step_one: prismic.ImageField<never>;

  /**
   * top text step one field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.top_text_step_one
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  top_text_step_one: prismic.RichTextField;

  /**
   * bottom text step one field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.bottom_text_step_one
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bottom_text_step_one: prismic.RichTextField;

  /**
   * button one text step one field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.button_one_text_step_one
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_one_text_step_one: prismic.KeyTextField;

  /**
   * button one link step one field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.button_one_link_step_one
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_one_link_step_one: prismic.LinkField;

  /**
   * button two text step one field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.button_two_text_step_one
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_two_text_step_one: prismic.KeyTextField;

  /**
   * button two link step one field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.button_two_link_step_one
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_two_link_step_one: prismic.LinkField;

  /**
   * label step two field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.label_step_two
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label_step_two: prismic.RichTextField;

  /**
   * image step two field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.image_step_two
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_step_two: prismic.ImageField<never>;

  /**
   * top text step two field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.top_text_step_two
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  top_text_step_two: prismic.RichTextField;

  /**
   * bottom text step two field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.bottom_text_step_two
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bottom_text_step_two: prismic.RichTextField;

  /**
   * button one text step two field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.button_one_text_step_two
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_one_text_step_two: prismic.KeyTextField;

  /**
   * button one link step two field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.button_one_link_step_two
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_one_link_step_two: prismic.LinkField;

  /**
   * button two text step two field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.button_two_text_step_two
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_two_text_step_two: prismic.KeyTextField;

  /**
   * button two link step two field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.button_two_link_step_two
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_two_link_step_two: prismic.LinkField;

  /**
   * label step three field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.label_step_three
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label_step_three: prismic.RichTextField;

  /**
   * image step three field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.image_step_three
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_step_three: prismic.ImageField<never>;

  /**
   * top text step three field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.top_text_step_three
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  top_text_step_three: prismic.RichTextField;

  /**
   * bottom text step three field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.bottom_text_step_three
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bottom_text_step_three: prismic.RichTextField;

  /**
   * button one text step three field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.button_one_text_step_three
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_one_text_step_three: prismic.KeyTextField;

  /**
   * button one link step three field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.button_one_link_step_three
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_one_link_step_three: prismic.LinkField;

  /**
   * button two text step three field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.button_two_text_step_three
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_two_text_step_three: prismic.KeyTextField;

  /**
   * button two link step three field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.button_two_link_step_three
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_two_link_step_three: prismic.LinkField;

  /**
   * button one text field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.button_one_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_one_text: prismic.KeyTextField;

  /**
   * button one link field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.button_one_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_one_link: prismic.LinkField;

  /**
   * button two text field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.button_two_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_two_text: prismic.KeyTextField;

  /**
   * button two link field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.button_two_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_two_link: prismic.LinkField;

  /**
   * background color field in *ThreeStepPlan → Slider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_step_plan.slider.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  background_color: prismic.KeyTextField;
}

/**
 * Slider variation for ThreeStepPlan Slice
 *
 * - **API ID**: `slider`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ThreeStepPlanSliceSlider = prismic.SharedSliceVariation<
  "slider",
  Simplify<ThreeStepPlanSliceSliderPrimary>,
  never
>;

/**
 * Slice variation for *ThreeStepPlan*
 */
type ThreeStepPlanSliceVariation =
  | ThreeStepPlanSliceDefault
  | ThreeStepPlanSliceClickthrough
  | ThreeStepPlanSliceSlider;

/**
 * ThreeStepPlan Shared Slice
 *
 * - **API ID**: `three_step_plan`
 * - **Description**: ThreeStepPlan
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ThreeStepPlanSlice = prismic.SharedSlice<
  "three_step_plan",
  ThreeStepPlanSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataS1SliderItem,
      HomeDocumentDataS2IconsItem,
      HomeDocumentDataS5SliderItem,
      HomeDocumentDataPartnersItem,
      HomeDocumentDataS7CitiesItem,
      HomeDocumentDataSlicesSlice,
      NavDocument,
      NavDocumentData,
      NavDocumentDataPartnersItem,
      NavDocumentDataVisitAddressesItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContentWidthMediaSlice,
      ContentWidthMediaSliceDefaultPrimary,
      ContentWidthMediaSliceSliderLeftImageRightPrimary,
      ContentWidthMediaSliceSliderLeftImageRightItem,
      ContentWidthMediaSliceTwoColImageAndTextPrimary,
      ContentWidthMediaSliceVariation,
      ContentWidthMediaSliceDefault,
      ContentWidthMediaSliceSliderLeftImageRight,
      ContentWidthMediaSliceTwoColImageAndText,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceSliderPrimary,
      HeroSliceSliderItem,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceSlider,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      ThreeStepPlanSlice,
      ThreeStepPlanSliceDefaultPrimary,
      ThreeStepPlanSliceClickthroughPrimary,
      ThreeStepPlanSliceSliderPrimary,
      ThreeStepPlanSliceVariation,
      ThreeStepPlanSliceDefault,
      ThreeStepPlanSliceClickthrough,
      ThreeStepPlanSliceSlider,
    };
  }
}
